ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 

CREATE USER SAMPLE IDENTIFIED BY 1234;

GRANT CONNECT, RESOURCE TO SAMPLE;


--문제에서 제시된 코드
SELECT EMP_NAME
       ,EMP_NO
       ,DEPT_CODE
       ,SALARY
FROM EMPLOYEE
WHERE DEPT_CODE='D9' OR DEPT_CODE='D6' 
--AND SALARY > 3000000
AND EMAIL LIKE '____%'
AND BONUS IS NULL;

--올바르게 고친 코드 
SELECT EMP_NAME
       ,EMP_NO
       ,DEPT_CODE
       ,SALARY
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D9','D6')
--WHERE DEPT_CODE='D9' OR DEPT_CODE = 'D6'
AND SALARY>=3000000
AND EMAIL LIKE '___\_%' ESCAPE '\'
AND BONUS IS NOT NULL;

SELECT EMP_NAME
       ,EMP_NO
       ,DEPT_CODE
       ,SALARY
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D9','D6')
AND SALARY>=3000000
AND EMAIL LIKE '___\_%' ESCAPE '\'
AND BONUS IS NOT NULL;​


-------------------------------------
SELECT EMP_NAME
       ,EMP_NO
       ,DEPT_CODE
       ,SALARY
FROM EMPLOYEE
--WHERE DEPT_CODE IN ('D9','D6')
WHERE DEPT_CODE='D9' OR DEPT_CODE = 'D6'
AND SALARY>=3000000
AND EMAIL LIKE '___\_%' ESCAPE '\'
AND BONUS IS NOT NULL;

--문제 3번

--문제의 코드
SELECT * 
FROM EMPLOYEE
WHERE BONUS=NULL
AND MANAGER_ID != NULL;

-- 내가 제시한 코드 
SELECT * 
FROM EMPLOYEE
WHERE BONUS IS NULL
AND MANAGER_ID IS NOT NULL;