/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-09 10:46:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1764557401970L));
    _jspx_dependants.put("jar:file:/C:/07_SpringWorkspace/springProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/views/common/menubar.jsp", Long.valueOf(1764989963397L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .content {\r\n");
      out.write("            background-color:rgb(247, 245, 245);\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .innerOuter {\r\n");
      out.write("            border:1px solid lightgray;\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            padding:5% 10%;\r\n");
      out.write("            background-color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table * {margin:5px;}\r\n");
      out.write("        table {width:100%;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <!-- jQuery 라이브러리 -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- 부트스트랩에서 제공하고 있는 스타일 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- 부트스트랩에서 제공하고 있는 스크립트 -->\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        div {box-sizing:border-box;}\r\n");
      out.write("        #header {\r\n");
      out.write("            width:80%;\r\n");
      out.write("            height:100px;\r\n");
      out.write("            padding-top:20px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        #header>div {width:100%; margin-bottom:10px;}\r\n");
      out.write("        #header_1 {height:40%;}\r\n");
      out.write("        #header_2 {height:60%;}\r\n");
      out.write("\r\n");
      out.write("        #header_1>div{\r\n");
      out.write("            height:100%;\r\n");
      out.write("            float:left;\r\n");
      out.write("        }\r\n");
      out.write("        #header_1_left {width:30%; position:relative;}\r\n");
      out.write("        #header_1_center {width:40%;}\r\n");
      out.write("        #header_1_right {width:30%;}\r\n");
      out.write("\r\n");
      out.write("        #header_1_left>img {height:80%; position:absolute; margin:auto; top:0px; bottom:0px; right:0px; left:0px;}\r\n");
      out.write("        #header_1_right {text-align:center; line-height:35px; font-size:12px; text-indent:35px;}\r\n");
      out.write("        #header_1_right>a {margin:5px;}\r\n");
      out.write("        #header_1_right>a:hover {cursor:pointer;}\r\n");
      out.write("\r\n");
      out.write("        #header_2>ul {width:100%; height:100%; list-style-type:none; margin:auto; padding:0;}\r\n");
      out.write("        #header_2>ul>li {float:left; width:25%; height:100%; line-height:55px; text-align:center;}\r\n");
      out.write("        #header_2>ul>li a {text-decoration:none; color:black; font-size:18px; font-weight:900;}\r\n");
      out.write("\r\n");
      out.write("        #header_2 {border-top:1px solid lightgray;}\r\n");
      out.write("\r\n");
      out.write("        #header a {text-decoration:none; color:black;}\r\n");
      out.write("\r\n");
      out.write("        /* 세부페이지마다 공통적으로 유지할 style */\r\n");
      out.write("        .content {\r\n");
      out.write("            background-color:rgb(247, 245, 245);\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .innerOuter {\r\n");
      out.write("            border:1px solid lightgray;\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            padding:5% 10%;\r\n");
      out.write("            background-color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- alertMsg 있으면 알림처리 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("        <div id=\"header_1\">\r\n");
      out.write("            <div id=\"header_1_left\">\r\n");
      out.write("                <img src=\"https://www.iei.or.kr/resources/images/common/top_logo_s.jpg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"header_1_center\"></div>\r\n");
      out.write("            <div id=\"header_1_right\">\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"header_2\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">HOME</a></li>\r\n");
      out.write("                <li><a href=\"\">공지사항</a></li>\r\n");
      out.write("                \r\n");
      out.write("                <!-- \r\n");
      out.write("                     list.bo 요청시 boardListView가 띄워지도록 해보기\r\n");
      out.write("                	 나머지 Board관련 클래스들 만들기 service,impl,dao,board VO까지\r\n");
      out.write("                	 boardListView() 메소드 \r\n");
      out.write("                	 게시글 목록 불러와서 boardListView.jsp 에 해당 목록 출력하기\r\n");
      out.write("                	 페이징처리도 해야하니 mybatisProject를 참고하여 페이징에 필요한 VO와 메소드를 활용하여\r\n");
      out.write("                	 페이징처리까지 해보기 rowBounds 사용하기\r\n");
      out.write("                	 mapper : board-mapper(namespace = boardMapper)\r\n");
      out.write("                	 alias : Board\r\n");
      out.write("                	 페이징에 필요한 VO 및 클래스 등은 common 패키지쪽에 넣어서 사용하기\r\n");
      out.write("                	 \r\n");
      out.write("                	 \r\n");
      out.write("                 -->\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/list.bo\">자유게시판</a></li>\r\n");
      out.write("                <!-- 자유게시판을 눌렀을때 BoardController에서 urlPattern이 /list.bo인곳으로 이동 -->\r\n");
      out.write("                <li><a href=\"\">사진게시판</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 로그인 클릭 시 뜨는 모달 (기존에는 안보이다가 위의 a 클릭 시 보임) -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"loginModal\">\r\n");
      out.write("        <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\">Login</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.me\" method=\"post\">\r\n");
      out.write("                    <!-- Modal body -->\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <label for=\"userId\" class=\"mr-sm-2\">ID : </label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"Enter ID\" id=\"userId\" name=\"userId\"> <br>\r\n");
      out.write("                        <label for=\"userPwd\" class=\"mr-sm-2\">Password : </label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"Enter Password\" id=\"userPwd\" name=\"userPwd\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                           \r\n");
      out.write("                    <!-- Modal footer -->\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <div class=\"innerOuter\">\r\n");
      out.write("            <h2>게시글 상세보기</h2>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <a class=\"btn btn-secondary\" style=\"float:right;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header.referer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">목록으로</a>\r\n");
      out.write("            <br><br>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	            <table id=\"contentArea\" algin=\"center\" class=\"table\">\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th width=\"100\">제목</th>\r\n");
      out.write("	                    <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>작성자</th>\r\n");
      out.write("	                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardWriter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	                    <th>작성일</th>\r\n");
      out.write("	                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.createDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>첨부파일</th>\r\n");
      out.write("	                    <td colspan=\"3\">\r\n");
      out.write("	                    	");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>내용</th>\r\n");
      out.write("	                    <td colspan=\"3\"></td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <td colspan=\"4\"><p style=\"height:150px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p></td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	            </table>\r\n");
      out.write("	            <br>\r\n");
      out.write("	            \r\n");
      out.write("	            \r\n");
      out.write("	            <div align=\"center\">\r\n");
      out.write("	                <!-- 수정하기, 삭제하기 버튼은 이 글이 본인이 작성한 글일 경우에만 보여져야 함 \r\n");
      out.write("	                	 boardUpdate()\r\n");
      out.write("	                	 update.bo \r\n");
      out.write("	                	 boardUpdateForm.jsp\r\n");
      out.write("	                -->\r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	            </div>\r\n");
      out.write("            \r\n");
      out.write("            <script>\r\n");
      out.write("            \r\n");
      out.write("            	$(function(){\r\n");
      out.write("            		replyList(); \r\n");
      out.write("            		//수정하기 또는 삭제하기 버튼 눌렀을때 url로 데이터 접근 및 요청이 불가능하도록 \r\n");
      out.write("            		//post방식으로 submit하기 스크립트 구문 작성\r\n");
      out.write("            		\r\n");
      out.write("            		/*\r\n");
      out.write("			           매번 form태그를 적기도 번거로운데 만약에 form태그가 get방식이면?\r\n");
      out.write("			           url을 보고 사용자가 마음대로 url링크를 조작해서 아무곳이나 다 들어갈수도있다.\r\n");
      out.write("			\r\n");
      out.write("			          그래서 post방식으로 작성을한다. \r\n");
      out.write("			        */\r\n");
      out.write("            		\r\n");
      out.write("            		$(\"#updateBtn\").click(function(){\r\n");
      out.write("            			//form태그 및 전달데이터 태그 작성하여 body영역에(문서) 추가하고 실행시키기(submit)\r\n");
      out.write("            			\r\n");
      out.write("            			//form에는 action과 method 추가 (서버에 요청용 form) \r\n");
      out.write("            			let form = $(\"<form>\").attr(\"action\",\"update.bo\").attr(\"method\",\"post\"); \r\n");
      out.write("            			//type,name,value 추가 (글번호 전달용 input)\r\n");
      out.write("            			let input = $(\"<input>\").attr(\"type\",\"hidden\").attr(\"name\",\"bno\").attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("            			\r\n");
      out.write("            			/*\r\n");
      out.write("            			let input = $(\"<input>\").attr(\"type\",\"hidden\").attr(\"name\",\"bno\").attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("            			\r\n");
      out.write("            			여기서 잘 보면 상세보기로 갈때는 모델에 보드 객체를 담아오기 때문에 \r\n");
      out.write("            			\r\n");
      out.write("            			수정하기 버튼을 누르기 전까지는 모델에 값이 있어서 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("가 가능하다. \r\n");
      out.write("            			*/\r\n");
      out.write("            			\r\n");
      out.write("            			\r\n");
      out.write("            			\r\n");
      out.write("            			//form태그에 input태그 넣기\r\n");
      out.write("            			form.append(input);\r\n");
      out.write("            			\r\n");
      out.write("						//form태그를 body태그영역에 추가하여 submit() 요청하기  			\r\n");
      out.write("            			$(\"body\").append(form);\r\n");
      out.write("						\r\n");
      out.write("						//서버에 submit 요청하기\r\n");
      out.write("						form.submit();\r\n");
      out.write("            		});\r\n");
      out.write("            		\r\n");
      out.write("            		\r\n");
      out.write("            		/*	\r\n");
      out.write("            			삭제하기 버튼 눌렀을때 이벤트 동작으로 처리하기 \r\n");
      out.write("            			confirm 을 이용하여 확인을 누르면 동작 처리\r\n");
      out.write("            			게시글 삭제 요청 매핑 : delete.bo\r\n");
      out.write("            			게시글 삭제 메소드 : deleteBoard() \r\n");
      out.write("            			db데이터를 삭제 한 이후에 해당 게시글에 첨부파일이 있다면 해당 첨부파일도 삭제하기\r\n");
      out.write("            		*/\r\n");
      out.write("						\r\n");
      out.write("            		$(\"#deleteBtn\").click(function(){\r\n");
      out.write("            			\r\n");
      out.write("            			let flag = confirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("            			\r\n");
      out.write("            			if(flag) {\r\n");
      out.write("            				\r\n");
      out.write("            				let form = $(\"<form>\").attr(\"action\",\"delete.bo\").attr(\"method\",\"post\");\r\n");
      out.write("\r\n");
      out.write("           	                let input = $(\"<input>\").attr(\"type\",\"hidden\").attr(\"name\",\"boardNo\").attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"); // 게시판 글 번호\r\n");
      out.write("\r\n");
      out.write("           	                let input2 = $(\"<input>\").attr(\"type\",\"hidden\").attr(\"name\",\"originName\").attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.originName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"); // 게시판 기존 파일 명\r\n");
      out.write("\r\n");
      out.write("           	                let input3 = $(\"<input>\").attr(\"type\",\"hidden\").attr(\"name\",\"changeName\").attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.changeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"); // 바뀐 파일 이름 \r\n");
      out.write("           	                \r\n");
      out.write("                            form.append(input); \r\n");
      out.write("           	                \r\n");
      out.write("           	                form.append(input2);\r\n");
      out.write("           	                \r\n");
      out.write("           	                form.append(input3); \r\n");
      out.write("\r\n");
      out.write("           	                $(\"body\").append(form);\r\n");
      out.write("\r\n");
      out.write("           	                form.submit();\r\n");
      out.write("\r\n");
      out.write("            				\r\n");
      out.write("            			}\r\n");
      out.write("            			\r\n");
      out.write("            			\r\n");
      out.write("            			/*\r\n");
      out.write("            			if(flag){\r\n");
      out.write("            				let form = $(\"<form>\").attr(\"action\",\"delete.bo\").attr(\"method\",\"post\");\r\n");
      out.write("            				let bnoInput = $(\"<input>\").attr(\"type\",\"hidden\")\r\n");
      out.write("            										   .attr(\"name\",\"bno\")\r\n");
      out.write("            										   .attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("            				\r\n");
      out.write("            				let filePath = $(\"<input>\").attr(\"type\",\"hidden\")\r\n");
      out.write("            										   .attr(\"name\",\"filePath\")\r\n");
      out.write("            										   .attr(\"value\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.changeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("            				\r\n");
      out.write("            				//form에 input 요소 추가하고 body에 추가하여 submit처리하기\r\n");
      out.write("            				form.append(bnoInput,filePath);\r\n");
      out.write("            				\r\n");
      out.write("            				$(\"body\").append(form);\r\n");
      out.write("            				\r\n");
      out.write("            				form.submit();\r\n");
      out.write("            			}\r\n");
      out.write("            			*/ \r\n");
      out.write("            		});\r\n");
      out.write("            		\r\n");
      out.write("            		\r\n");
      out.write("            		\r\n");
      out.write("            		\r\n");
      out.write("            	});\r\n");
      out.write("            	\r\n");
      out.write("            	/*\r\n");
      out.write("            	    매핑 주소 및 메소드명 : replyList / selectList.re\r\n");
      out.write("            	    \r\n");
      out.write("            	    해당 상세 페이지 들어오면 비동기 요청 처리되어 댓글 목록 불러오기\r\n");
      out.write("            	    \r\n");
      out.write("            	    댓글 개수도 추가 (rcount 위치)\r\n");
      out.write("            	\r\n");
      out.write("            	    model은 VO 제외 board꺼 사용하기 mapper도 마찬가지 \r\n");
      out.write("            	*/\r\n");
      out.write("            	\r\n");
      out.write("            	function replyList() {\r\n");
      out.write("				     \r\n");
      out.write("				    $.ajax({\r\n");
      out.write("				    	url : \"selectList.re\",\r\n");
      out.write("				    	data : {\r\n");
      out.write("				    		//어떤 게시글에 달린 댓글인지 알아야하기 때문에 참조 게시글 번호 전달 \r\n");
      out.write("				    		refBno : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				    	},\r\n");
      out.write("				    	success : function(list){\r\n");
      out.write("				    		\r\n");
      out.write("				    		console.log(list);\r\n");
      out.write("				    		\r\n");
      out.write("				    		\r\n");
      out.write("							for(let m of list) {\r\n");
      out.write("								\r\n");
      out.write("								let tr = $(\"<tr>\");\r\n");
      out.write("								tr.append($(\"<td>\").text(m.replyWriter)\r\n");
      out.write("										  ,$(\"<td>\").text(m.replyContent)\r\n");
      out.write("										  ,$(\"<td>\").text(m.createDate));\r\n");
      out.write("					\r\n");
      out.write("					            $(\"#replyArea tbody\").append(tr);\r\n");
      out.write("					            \r\n");
      out.write("					             \r\n");
      out.write("					            \r\n");
      out.write("					            \r\n");
      out.write("					\r\n");
      out.write("								\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("							$(\"#replyArea #rcount\").text(list.length);\r\n");
      out.write("				    		\r\n");
      out.write("				    	},\r\n");
      out.write("				    	error : function(){\r\n");
      out.write("				    		console.log(\"통신 오류\");\r\n");
      out.write("				    		\r\n");
      out.write("				    	}\r\n");
      out.write("				    	\r\n");
      out.write("				    })	\r\n");
      out.write("				}\r\n");
      out.write("            	\r\n");
      out.write("            	/*\r\n");
      out.write("            	   댓글 등록하기 버튼 누르면 해당 댓글내용 등록처리하기\r\n");
      out.write("            	   insertReply.re 매핑명\r\n");
      out.write("            	   insertReply() 메소드명\r\n");
      out.write("            	   등록 후 목록이 갱신될 수 있도록 처리하기\r\n");
      out.write("            	   댓글 등록은 로그인된 상태에서만 가능하도록 처리할것. \r\n");
      out.write("            	   \r\n");
      out.write("            	   성공/실패 여부는 alert 메시지로 처리(댓글 등록 성공! / 댓글 등록 실패!)\r\n");
      out.write("            	*/\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	/*\r\n");
      out.write("            	$(function(){\r\n");
      out.write("\r\n");
      out.write("            	    $(\"#replyBtn\").click(function(){\r\n");
      out.write("\r\n");
      out.write("            	        $.ajax({\r\n");
      out.write("            	            url: \"insertReply.re\",\r\n");
      out.write("            	            data: {\r\n");
      out.write("            	                replyContent: $(\"#content\").val(),\r\n");
      out.write("            	                replyWriter: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",  // <-- 문자열 처리 중요\r\n");
      out.write("            	                refBno: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            	            },\r\n");
      out.write("            	            success: function(result){\r\n");
      out.write("            	                alert(result);\r\n");
      out.write("            	            },\r\n");
      out.write("            	            error: function(){\r\n");
      out.write("            	                alert(\"댓글 작성 실패!\");\r\n");
      out.write("            	            }\r\n");
      out.write("            	        });\r\n");
      out.write("\r\n");
      out.write("            	    });\r\n");
      out.write("\r\n");
      out.write("            	});\r\n");
      out.write("            	*/\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	//console.log(\"#replyArea>thead>tr button\")\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	//내가 짠 코드\r\n");
      out.write("            	$(function(){\r\n");
      out.write("            		\r\n");
      out.write("            		$(\"#replyArea>thead>tr button\").click(function(){\r\n");
      out.write("                		\r\n");
      out.write("                		$.ajax({\r\n");
      out.write("                			url : \"insertReply.re\",\r\n");
      out.write("                			\r\n");
      out.write("                			data : {\r\n");
      out.write("                				replyContent : $(\"#replyArea>thead>tr>th #content\").val(),\r\n");
      out.write("                				//사용자가 내용란에 댓글을 입력하는 것을 갖고오기 \r\n");
      out.write("                				//$(\"#content\").val()\r\n");
      out.write("                				\r\n");
      out.write("                		        replyWriter : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("                		        //댓글 작성자랑 로그인한 회원의 userId와 같으니까 갖고오기 \r\n");
      out.write("                		        \r\n");
      out.write("                		        refBno : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                		        //데이터베이스에 댓글을 보관할때 어떤 게시판의 글에서 썼는지를 알고 댓글을 등록해야 하니까\r\n");
      out.write("                		        //게시판 참조번호를 현재 상세보기 뷰에 있는 boardNo를 갖고온다. \r\n");
      out.write("                		        \r\n");
      out.write("                			},\r\n");
      out.write("                			\r\n");
      out.write("                			success : function(data) {			\r\n");
      out.write("                				alert(data);\r\n");
      out.write("                			},\r\n");
      out.write("                			\r\n");
      out.write("                			error : function() {\r\n");
      out.write("                				alert(\"댓글 등록 실패!\");\r\n");
      out.write("                			}\r\n");
      out.write("                			\r\n");
      out.write("                			\r\n");
      out.write("                		});\r\n");
      out.write("                		\r\n");
      out.write("                	}); \r\n");
      out.write("            		\r\n");
      out.write("            	});\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            	\r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <br><br>\r\n");
      out.write("\r\n");
      out.write("            <!-- 댓글 기능은 나중에 ajax 배우고 나서 구현할 예정! 우선은 화면구현만 해놓음 -->\r\n");
      out.write("            <table id=\"replyArea\" class=\"table\" align=\"center\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th colspan=\"2\">\r\n");
      out.write("                            <textarea class=\"form-control\" placeholder=\"로그인 후 이용가능합니다.\" id=\"content\" cols=\"55\" rows=\"2\" style=\"resize:none; width:100%;\"></textarea>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <th style=\"vertical-align:middle\">\r\n");
      out.write("                           ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("                        </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                       \r\n");
      out.write("                        <td colspan=\"3\">댓글(<span id=\"rcount\">3</span>)</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                \r\n");
      out.write("                    <!--  \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>user02</th>\r\n");
      out.write("                        <td>ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ꿀잼</td>\r\n");
      out.write("                        <td>2020-03-12</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    -->\r\n");
      out.write("                    \r\n");
      out.write("                             \r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        \r\n");
      out.write("		        /*\r\n");
      out.write("				    매핑 주소 및 메소드명 : replyList / selectList.re\r\n");
      out.write("				    \r\n");
      out.write("				    해당 상세 페이지 들어오면 비동기 요청 처리되어 댓글 목록 불러오기\r\n");
      out.write("				    \r\n");
      out.write("				    댓글 개수도 추가 (rcount 위치)\r\n");
      out.write("				\r\n");
      out.write("				    model은 VO 제외 board꺼 사용하기 mapper도 마찬가지 \r\n");
      out.write("				*/\r\n");
      out.write("				\r\n");
      out.write("				/*\r\n");
      out.write("				function replyList() {\r\n");
      out.write("				     \r\n");
      out.write("				    $.ajax({\r\n");
      out.write("				    	url : \"selectList.re\",\r\n");
      out.write("				    	data : {\r\n");
      out.write("				    		//어떤 게시글에 달린 댓글인지 알아야하기 때문에 참조 게시글 번호 전달 \r\n");
      out.write("				    		refBno : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				    	},\r\n");
      out.write("				    	success : function(list){\r\n");
      out.write("				    		\r\n");
      out.write("				    		console.log(list);\r\n");
      out.write("				    		\r\n");
      out.write("				    	},\r\n");
      out.write("				    	error : function(){\r\n");
      out.write("				    		console.log(\"통신 오류\");\r\n");
      out.write("				    		\r\n");
      out.write("				    	}\r\n");
      out.write("				    	\r\n");
      out.write("				    })	\r\n");
      out.write("				}\r\n");
      out.write("                */\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				/*\r\n");
      out.write("				$(function(){\r\n");
      out.write("					\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"selectList.re\",\r\n");
      out.write("						\r\n");
      out.write("						success : function(list) {\r\n");
      out.write("							let count = 0; \r\n");
      out.write("							for(let m of list) {\r\n");
      out.write("								\r\n");
      out.write("								let tr = $(\"<tr>\");\r\n");
      out.write("								tr.append($(\"<td>\").text(m.replyWriter)\r\n");
      out.write("										  ,$(\"<td>\").text(m.replyContent)\r\n");
      out.write("										  ,$(\"<td>\").text(m.createDate));\r\n");
      out.write("					\r\n");
      out.write("					            $(\"#replyArea tbody\").append(tr);\r\n");
      out.write("					            \r\n");
      out.write("					            count=count+1; \r\n");
      out.write("					            \r\n");
      out.write("					            \r\n");
      out.write("					\r\n");
      out.write("								\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("							$(\"#replyArea #rcount\").text(count);\r\n");
      out.write("						},\r\n");
      out.write("						\r\n");
      out.write("						error : function(){\r\n");
      out.write("							console.log(\"통신 실패!\"); \r\n");
      out.write("						}\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("				})\r\n");
      out.write("				*/\r\n");
      out.write("				\r\n");
      out.write("				/*\r\n");
      out.write("				$(\"#replyBtn\").click(function(){\r\n");
      out.write("					\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"insertReply.re\",\r\n");
      out.write("						data : {\r\n");
      out.write("							\r\n");
      out.write("							replyContent : $(\"#content\").val(),\r\n");
      out.write("							replyWriter : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("							refBno : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("							\r\n");
      out.write("						},\r\n");
      out.write("						\r\n");
      out.write("						success : function(result) {\r\n");
      out.write("							\r\n");
      out.write("							if(result > 0) {\r\n");
      out.write("								alert(\"댓글 작성 성공!\");\r\n");
      out.write("							} else {\r\n");
      out.write("								alert(\"댓글 작성 실패!\");\r\n");
      out.write("							}\r\n");
      out.write("							\r\n");
      out.write("						},\r\n");
      out.write("						\r\n");
      out.write("						error : function() {\r\n");
      out.write("							       alert(\"통신 실패!\");\r\n");
      out.write("						        }\r\n");
      out.write("						\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("				*/\r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/common/menubar.jsp(65,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextRoot");
    // /WEB-INF/views/common/menubar.jsp(65,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/menubar.jsp(65,1) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/common/menubar.jsp(68,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty alertMsg }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("		<script>\r\n");
        out.write("			alert(\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alertMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\");\r\n");
        out.write("		</script>\r\n");
        out.write("		\r\n");
        out.write("		<!-- 알림메시지 지워주기 -->\r\n");
        out.write("		");
        if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/common/menubar.jsp(74,2) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setVar("alertMsg");
    int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
    if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("               ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/common/menubar.jsp(86,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginMember }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                	<!-- 회원가입 페이지 이동 및 회원가입 처리 해보기 \r\n");
        out.write("                		 페이지 이동 메소드명 : enrollForm()\r\n");
        out.write("                		 페이지 이동 매핑주소 : enrollForm.me\r\n");
        out.write("                		 회원가입 요청 메소드명 : insertMember()\r\n");
        out.write("                		 회원가입 요청 매핑주소 : insert.me\r\n");
        out.write("                		 \r\n");
        out.write("                		 회원가입 처리시 나이를 꼭 입력할것 만약 입력하지 않은 경우 나는 400번 오류를 \r\n");
        out.write("                		 해결할 방법도 생각해보기 \r\n");
        out.write("                		 회원가입 성공시 : 메인페이지로 이동(재요청) 및 회원가입 성공! 메시지 alert 띄우기 \r\n");
        out.write("                		 회원가입 실패시 : 에러페이지로 이동(재요청) 및 회원가입 실패! 메시지 h1요소에 띄우기 \r\n");
        out.write("                		 \r\n");
        out.write("                	 -->\r\n");
        out.write("                	\r\n");
        out.write("	                <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/enrollForm.me\">회원가입</a>\r\n");
        out.write("    	            <a data-toggle=\"modal\" data-target=\"#loginModal\">로그인</a> <!-- 모달의 원리 : 이 버튼 클릭시 data-targer에 제시되어있는 해당 아이디의 div요소를 띄워줌 -->\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                <!-- 로그인 후 -->\r\n");
        out.write("                    <lable>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("님 환영합니다</label> &nbsp;&nbsp;\r\n");
        out.write("                    <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/mypage.me\">마이페이지</a>\r\n");
        out.write("                    <!-- 마이페이지 이동하기 / 메소드명 mypage() / 매핑주소 : mypage.me -->\r\n");
        out.write("                    <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/logout.me\">로그아웃</a>\r\n");
        out.write("                    <!-- 로그아웃 처리 하기 메소드명 logout() / 매핑주소 : logout.me / 처리 후 이전 경로로 이동되도록 처리하기 -->\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("	                    		");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("	                    		");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("	                    	");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /WEB-INF/views/board/boardDetailView.jsp(58,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty b.originName }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("	                    			첨부파일이 없습니다.\r\n");
        out.write("	                    		");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("			                        <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextRoot}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.changeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" download=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.originName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.originName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a>\r\n");
        out.write("			                        ");
        out.write("\r\n");
        out.write("	                    		");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/board/boardDetailView.jsp(85,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.userId eq b.boardWriter}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("	                \r\n");
        out.write("<!-- 						<form action=\"update.bo\" method=\"post\"> -->\r\n");
        out.write("\r\n");
        out.write("		                	<button type=\"button\" id='updateBtn' class=\"btn btn-primary\">수정하기</button>\r\n");
        out.write("<!-- 			            </form> -->\r\n");
        out.write("                            ");
        out.write("   \r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("			            \r\n");
        out.write("<!-- 						<form action=\"delete.bo\" method=\"post\"> -->\r\n");
        out.write("		                	<button type=\"button\" id=\"deleteBtn\" class=\"btn btn-danger\">삭제하기</button>\r\n");
        out.write("<!-- 		                </form> -->\r\n");
        out.write("	                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/views/board/boardDetailView.jsp(354,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginMember}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                              <button class=\"btn btn-secondary\" id=\"replyBtn\">등록하기</button>\r\n");
        out.write("                           ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
